#!/usr/bin/env bash

# TODO - 

# Quando se tratar de scripts, utilizar o path inteiro
init_once(){
	{
		[[ $(pidof -sx "$1") ]] || [[ $(pgrep -f "$1" ) ]] 
	} || $1 &
}

config_mouse_pad(){
	local mouse_id=$(xinput list | sed -n "/ETPS\/2 Elantech Touchpad/s/.*id=\([0-9]\+\).*/\1/p")
	local IFS=$'\n'
	local props=($(xinput list-props "$mouse_id" | grep --color=never "Natural Scrolling Enabled (\|Accel Speed (" | sed "s/.*(\([0-9]\+\)).*/\1/g"))
	# Natural Scroll
	xinput set-prop "$mouse_id" "${props[0]}" 1 &
	# Accel Speed
	xinput set-prop "$mouse_id" "${props[1]}" 1.0 &
}

# Inicialização
init_once sxhkd
init_once udiskie
init_once transmission-daemon
init_once ~/.config/bspwm/bspl
init_once ~/.local/bin/battery_alarm

polybar andrikin_bar &
brave-browser-stable &
numlockx on &
config_mouse_pad
feh --bg-scale "/home/andre/Imagens/Minas Tirith.jpg" &

# Configurações BSPC
bspc monitor -d I II III IV V

bspc config border_width        1
bspc config focused_border_color "#ffffff"
bspc config window_gap          0

# Interações com Mouse
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config single_monocle		 true

bspc rule -a Brave desktop='^1'
bspc rule -a Transmission-gtk desktop='^5'
bspc rule -a discord desktop='^5'
bspc rule -a vlc state=floating
